[package]
name = "fea-rs-ast"
version = "0.1.0"
edition = "2024"
description = "fontTools-like AST wrapper around fea-rs parser"

[dependencies]
fea-rs = { version = "0.21.0" }
smol_str = "0.3.4"
[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"
